=== zhenekq/xml_parser/target/xml-validator-1.0-SNAPSHOT/tariffs.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="mobile-company">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="name" type="xsd:string"/>
                <xsd:element name="foundation" type="xsd:date"/>
                <xsd:element name="tariffs" type="tariffs"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:complexType name="tariffs">
        <xsd:sequence>
            <xsd:element name="tariff" type="tariff"/>
        </xsd:sequence>
    </xsd:complexType>

    <!--TARIFF DESCRIPTION-->
    <xsd:complexType name="tariff">
        <xsd:sequence>
            <xsd:element name="tariff_name" type="xsd:string" />
            <xsd:element name="payroll">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:decimal">
                        <xsd:minInclusive value="0.0"/>
                        <xsd:maxInclusive value="5.20"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="calls" type="calls"/>
            <xsd:element name="sms_price">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:decimal">
                        <xsd:minInclusive value="0.0"/>
                        <xsd:maxInclusive value="1.0"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="parameters" type="parameters"/>
        </xsd:sequence>
        <xsd:attribute name="tariff_id" type="xsd:ID" use="required"/>
    </xsd:complexType>


    <xsd:complexType name="calls">
        <xsd:sequence>
            <xsd:element name="call" type="call"/>
        </xsd:sequence>

    </xsd:complexType>

    <!--CALL DESCRIPTION-->
    <xsd:complexType name="call">
        <xsd:sequence>
            <xsd:element name="call_name" type="xsd:string"/>
            <xsd:element name="call_price">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:decimal">
                        <xsd:minInclusive value="0.0"/>
                        <xsd:maxInclusive value="2.1"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
        </xsd:sequence>
        <xsd:attribute name="call_id" type="xsd:ID" use="required"/>
    </xsd:complexType>

    <!--PARAMETER DESCRIPTION-->
    <xsd:complexType name="parameters">
        <xsd:sequence>
            <xsd:element name="parameter" type="parameter"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="parameter">
        <xsd:sequence>
            <xsd:element name="parameter_name" type="xsd:string"/>
            <xsd:element name="parameter_amount" type="xsd:string"/>
        </xsd:sequence>
        <xsd:attribute name="parameter_id" type="xsd:ID" use="required"/>
    </xsd:complexType>

</xsd:schema>

=== zhenekq/xml_parser/src/main/webapp/tariffs.xml
<?xml version="1.0" encoding="UTF-8" ?>
<mobile-company xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="tariffs.xsd"
                xmlns="file://D:/folderWithAllDevelopmentOnThisPC/Servlets/XML_VALIDATOR/src/main/webapp/tariffs.xsd">
    <name>MTC-COMPANY</name>
    <foundation>12.03.2010</foundation>
    <tariffs>
        <tariff tariff_id="tariff_1">
            <tariff_name>MTC-BONUS</tariff_name>
            <payroll>1.3</payroll>
            <calls>
                <call call_id="call_1">
                    <call_name>Out of network</call_name>
                    <call_price>1.2</call_price>
                </call>
                <call call_id="call_2">
                    <call_name>In network</call_name>
                    <call_price>0.6</call_price>
                </call>
                <call call_id="call_3">
                    <call_name>Stationary</call_name>
                    <call_price>0.9</call_price>
                </call>
            </calls>
            <sms_price>0.5</sms_price>
            <parameters>
                <parameter parameter_id="parameter_1">
                    <parameter_name>favorite_number</parameter_name>
                    <parameter_amount>5</parameter_amount>
                </parameter>
                <parameter parameter_id="parameter_2">
                    <parameter_name>tariff-ing</parameter_name>
                    <parameter_amount>12-sec</parameter_amount>
                </parameter>
                <parameter parameter_id="parameter_3">
                    <parameter_name>connect_price</parameter_name>
                    <parameter_amount>12.3</parameter_amount>
                </parameter>
            </parameters>
        </tariff>
    </tariffs>
</mobile-company>
